### ISSUE TITLE
rename repository

### ISSUE THREAD

**Issue by sergiors** [dlang-tour/brazilian-portuguese#2]
@wilzbach could you rename the repository name to `brazilian-portuguese`?

@FFY00 would like to translate dlang-tour into Portugal's portuguese, could you clone `english` to `portuguese` and add he?

**Comment by wilzbach** [comment]
Oh I always thought that there's such a huge difference between these two languages and considering that the Brazilian Portuguese translation has only two pages translated, it might be worthwhile to join efforts, no?
(there's also only one French and German translation even though these language have many sub dialects too.)

Anyway, I renamed the repository, created the new one and invited @FFY00, 

https://github.com/dlang-tour/core/pull/713
https://github.com/dlang-tour/brazilian-portuguese/pull/3
https://github.com/dlang-tour/portuguese

**Comment by wilzbach** [comment]
> could you clone english

I didn't clone English to avoid the content getting outdated with upstream. This will happen anyway with a translation, but there's no reason to preemptively do so.
If it helps the reviewers, one can always easily commit the snapshot of a few files from upstream.

**Comment by sergiors** [comment]
Thanks @wilzbach!

It's a great idea! We will do it.
> it might be worthwhile to join efforts, no?
